import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Navigation from "@/utils/Navigation";
import PageTransitionController from "@/components/PageTransitionController";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
  <Navigation href="/signup" label="Sign up" className="fixed right-0 z-100 border-amber-500 border-8 w-fit" />
  <Navigation href="/" label="Home" className="fixed z-100 border-amber-500 border-8 w-fit" />
  <PageTransitionController />
  {children}
        <Toaster />
      </body>
    </html>
  );
}
